name = "teaz-vpn-bot"
compatibility_date = "2026-01-02"
main = "main.js"
workers_dev = true

[vars]
BOT_TOKEN = "7084280622:AAGlwBy4FmMM3mc4OjjLQqa00Cg4t3jJzNg"
CHANNEL_USERNAME = "@teazvpn"
ADMIN_ID = "5542927340"
