name = "teaz-vpn-bot"
main = "main.js"
compatibility_date = "2026-01-02"
workers_dev = true

[vars]
CHANNEL_USERNAME = "@teazvpn"
ADMIN_ID = "5542927340"
TRON_ADDRESS = "TJ4xrwKzKjk6FgKfuuqwah3Az5Ur22kJb"
BANK_CARD = "6037 9975 9717 2684"
BOT_USERNAME = "teazvpn_bot"
